import { Injectable } from '@angular/core';

import { InMemoryDbService } from 'angular-in-memory-web-api';

@Injectable({
  providedIn: 'root',
})
export class DataService implements InMemoryDbService {
  constructor() {}

  createDb() {
    let specialityList = [
      {
        id: 1,
        key: '1',
        speciality: 'Painting',
        date: 'Wed Mar 07 2020 10:04:48 GMT+0530 (India Standard Time)',
        img: 'assets/img/user/user1.jpg',
        checked: true,
      },
      {
        id: 2,
        key: '2',
        speciality: 'Interior',
        date: 'Wed Mar 07 2020 10:04:48 GMT+0530 (India Standard Time)',
        img: 'assets/img/user/user2.jpg',
        checked: true,
      },
      {
        id: 3,
        key: '3',
        speciality: 'Electrical',
        date: 'Wed Mar 07 2020 10:04:48 GMT+0530 (India Standard Time)',
        img: 'assets/img/user/user3.jpg',
        checked: false,
      },
      {
        id: 4,
        key: '4',
        speciality: 'Construction',
        date: 'Wed Mar 07 2020 10:04:48 GMT+0530 (India Standard Time)',
        img: 'assets/img/user/user4.jpg',
        checked: false,
      },
      {
        id: 5,
        key: '5',
        speciality: 'Computer',
        date: 'Wed Mar 07 2020 10:04:48 GMT+0530 (India Standard Time)',
        img: 'assets/img/user/user5.jpg',
        checked: true,
      },
      {
        id: 6,
        key: '6',
        speciality: 'Cleaning',
        date: 'Wed Mar 07 2020 10:04:48 GMT+0530 (India Standard Time)',
        img: 'assets/img/user/user6.jpg',
        checked: true,
      },
      {
        id: 7,
        key: '7',
        speciality: 'Carpentry',
        date: 'Wed Mar 07 2020 10:04:48 GMT+0530 (India Standard Time)',
        img: 'assets/img/user/user7.jpg',
        checked: true,
      },
    ];

    let appointments = [
      {
        id: 1,
        doctorName: 'Ruby Perrin',
        type: 'Maths',
        docImg: 'assets/img/user/user.jpg',
        speciality: 'Java Script',
        patient_key: '01',
        Patient_Name: 'Charlene Reed',
        appointment_time:
          'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        status: 'accepted',
        amount: '$200.00',
      },
      {
        id: 2,
        doctorName: 'Darren Eldder',
        docImg: 'assets/img/user/user1.jpg',
        type: 'HTML',
        speciality: 'Maths',
        patient_key: '15',
        Patient_Name: 'Travis Trimble',
        appointment_time:
          'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        status: 'pending',
        amount: '$300.00',
      },
      {
        id: 3,
        doctorName: 'Deborah Angel',
        docImg: 'assets/img/user/user2.jpg',
        type: 'Developer',
        speciality: 'Algebra',
        patient_key: '03',
        Patient_Name: 'Carl Kelly',
        appointment_time:
          'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        status: 'accepted',
        amount: '$150.00',
      },
      {
        id: 4,
        doctorName: 'Sofia Brient',
        docImg: 'assets/img/user/user3.jpg',
        type: 'ARMS University Ranker',
        speciality: 'Flow chart',
        patient_key: '04',
        Patient_Name: 'Michelle Fairfax',
        appointment_time:
          'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        status: 'pending',
        amount: '$150.00',
      },
      {
        id: 5,
        doctorName: 'Marvin Campbell',
        docImg: 'assets/img/user/user4.jpg',
        type: 'Developer',
        speciality: 'Integrated Sum',
        patient_key: '05',
        Patient_Name: 'Gina Moore',
        appointment_time:
          'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        status: 'rejected',
        amount: '$200.00',
      },
    ];

    let favourites = [
      {
        id: 1,
        doctor_name: 'Ruby Perrin',
        speciality: 'Dentist',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'Digital Marketer',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '3100.00',
        Price: '$160',
        profile: 'assets/img/user/user4.jpg',
        status: '1',
        type: 'Female',
        location: 'Georgia, USA',
        availableTime: '10 am',
        consulting_fees: '$1000',
        booking_fees: '$300',
        video_call: '$50',
      },
      {
        id: 2,
        doctor_name: 'Darren Elder',
        speciality: 'Surgery',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'UNIX, Calculus, Trigonometry',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '3900.00',
        Price: '$190',
        profile: 'assets/img/user/user5.jpg',
        status: '1',
        type: 'Female',
        location: 'Montana, USA',
        availableTime: '8 am',
        consulting_fees: '$900',
        booking_fees: '$500',
        video_call: '$50',
      },
      {
        id: 3,
        doctor_name: 'Deborah Angel',
        speciality: 'Algebra',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'Computer Programming',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '3700.00',
        Price: '$170',
        profile: 'assets/img/user/user6.jpg',
        status: '1',
        type: 'Female',
        location: 'Oklahoma, USA',
        availableTime: '2 pm',
        consulting_fees: '$700',
        booking_fees: '$600',
        video_call: '$50',
      },
      {
        id: 4,
        doctor_name: 'Sofia Brient',
        speciality: 'BDS, MDS - Oral & Maxillofacial Surgery',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'ASP.NET,Computer Gaming',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '3000.00',
        Price: '$110',
        profile: 'assets/img/user/user7.jpg',
        status: '1',
        type: 'Female',
        location: 'Georgia, USA',
        availableTime: '11 am',
        consulting_fees: '$500',
        booking_fees: '$300',
        video_call: '$50',
      },
      {
        id: 5,
        doctor_name: 'Marvin Campbell',
        speciality: 'MBBS, MD - Ophthalmology, DNB - Ophthalmology',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'Digital Marketer',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '3150.00',
        Price: '$130',
        profile: 'assets/img/user/user8.jpg',
        status: '1',
        type: 'Male',
        location: 'Florida, USA',
        availableTime: '12 pm',
        consulting_fees: '$800',
        booking_fees: '$400',
        video_call: '$50',
      },
      {
        id: 6,
        doctor_name: 'Katharine Berthold',
        speciality: 'Dentist',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'UNIX, Calculus, Trigonometry',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '2900.00',
        Price: '$180',
        profile: 'assets/img/user/user9.jpg',
        status: '1',
        type: 'Female',
        location: 'Newyork, USA',
        availableTime: '7 am',
        consulting_fees: '$700',
        booking_fees: '$500',
        video_call: '$50',
      },
      {
        id: 7,
        doctor_name: 'Linda Tobin',
        speciality: 'Dentist',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'General Course',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '2900.00',
        Price: '$160',
        profile: 'assets/img/user/user10.jpg',
        status: '1',
        type: 'Female',
        location: 'Texas, USA',
        availableTime: '10 pm',
        consulting_fees: '$300',
        booking_fees: '$100',
        video_call: '$50',
      },
      {
        id: 8,
        doctor_name: 'Julia Washington',
        speciality: 'Dentist',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'ASP.NET,Computer Gaming',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '3200.00',
        Price: '$140',
        profile: 'assets/img/user/user11.jpg',
        status: '1',
        type: 'Female',
        location: 'Louisiana, USA',
        availableTime: '9 am',
        consulting_fees: '$950',
        booking_fees: '$650',
        video_call: '$50',
      },
      {
        id: 9,
        doctor_name: 'Paul Richard',
        speciality: 'Dentist',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'Digital Marketer',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '3000.00',
        Price: '$150',
        profile: 'assets/img/user/user12.jpg',
        status: '1',
        type: 'Male',
        location: 'Louisiana, USA',
        availableTime: '10 am',
        consulting_fees: '$850',
        booking_fees: '$800',
        video_call: '$50',
      },
    ];

    let mentors = [
      {
        id: 1,
        doctor_name: 'Ruby Perrin',
        speciality: 'Flow chart',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Education: 'Digital Marketer',
        Available: ' Available on Fri, 22 Mar ',
        Earned: '3100.00',
        Price: '$160',
        profile: 'assets/img/user/user.jpg',
        status: '1',
        type: 'Female',
        location: 'Georgia, USA',
        availableTime: '10 am',
        consulting_fees: '$500',
        booking_fees: '$400',
        video_call: '$50',
      },
      {
        id: 2,
        doctor_name: 'Darren Elder',
        speciality: 'Algebra',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Earned: '5000.00',
        Education: 'Digital Marketer',
        Available: ' Available on Fri, 22 Mar ',
        Price: ' $150 - $250 ',
        status: '1',
        profile: 'assets/img/user/user1.jpg',
        type: 'Female',
        location: 'Louisiana, USA',
        availableTime: '10 am',
        consulting_fees: '$1000',
        booking_fees: '$800',
        video_call: '$50',
      },
      {
        id: 3,
        doctor_name: 'Deborah Angel',
        speciality: 'Flow chart',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Earned: '3300.00',
        Education: 'Computer Programming',
        Available: ' Available on Fri, 22 Mar ',
        Price: '$210',
        status: '1',
        profile: 'assets/img/user/user2.jpg',
        type: 'Male',
        location: 'Georgia, USA',
        availableTime: '3 pm',
        consulting_fees: '$500',
        booking_fees: '$400',
        video_call: '$50',
      },
      {
        id: 4,
        doctor_name: 'Sofia Brient',
        speciality: 'Maths',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Earned: '3500.00',
        Education: 'ASP.NET,Computer Gaming',
        Available: ' Available on Fri, 22 Mar ',
        Price: '$310',
        status: '1',
        profile: 'assets/img/user/user3.jpg',
        type: 'Male',
        location: 'Newyork, USA',
        availableTime: '12 am',
        consulting_fees: '$500',
        booking_fees: '$400',
        video_call: '$50',
      },
      {
        id: 5,
        doctor_name: 'Katharine Berthold',
        speciality: 'Business Maths',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Earned: '3700.00',
        Education: 'UNIX,Calculus,Trigonometry',
        Available: ' Available on Fri, 22 Mar ',
        Price: '$260',
        status: '1',
        profile: 'assets/img/user/user4.jpg',
        type: 'Male',
        location: 'Florida, USA',
        availableTime: '11 am',
        consulting_fees: '$700',
        booking_fees: '$500',
        video_call: '$50',
      },
      {
        id: 6,
        doctor_name: 'Marvin Campbell',
        speciality: 'Math Grade II',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Earned: '3700.00',
        Education: 'UNIX,Calculus,Trigonometry',
        Available: ' Available on Fri, 22 Mar ',
        Price: '$260',
        status: '1',
        profile: 'assets/img/user/user5.jpg',
        type: 'Male',
        location: 'Florida, USA',
        availableTime: '11 am',
        consulting_fees: '$450',
        booking_fees: '$400',
        video_call: '$50',
      },
      {
        id: 7,
        doctor_name: 'Olga Barlow',
        speciality: 'Integrated Sum',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Earned: '3700.00',
        Education: 'Computer Programming',
        Available: ' Available on Fri, 22 Mar ',
        Price: '$260',
        status: '1',
        profile: 'assets/img/user/user6.jpg',
        type: 'Male',
        location: 'Florida, USA',
        availableTime: '11 am',
        consulting_fees: '$600',
        booking_fees: '$400',
        video_call: '$50',
      },
      {
        id: 8,
        doctor_name: 'Paul Richard',
        speciality: 'Basic Calculation',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Earned: '3700.00',
        Education: 'Digital Marketer',
        Available: ' Available on Fri, 22 Mar ',
        Price: '$260',
        status: '1',
        profile: 'assets/img/user/user7.jpg',
        type: 'Male',
        location: 'Florida, USA',
        availableTime: '11 am',
        consulting_fees: '$2000',
        booking_fees: '$1500',
        video_call: '$50',
      },
      {
        id: 9,
        doctor_name: 'Ruby Perrin',
        speciality: 'Maths',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Earned: '3700.00',
        Education: 'Digital Marketer',
        Available: ' Available on Fri, 22 Mar ',
        Price: '$260',
        status: '1',
        profile: 'assets/img/user/user8.jpg',
        type: 'Male',
        location: 'Florida, USA',
        availableTime: '11 am',
        consulting_fees: '$950',
        booking_fees: '$700',
        video_call: '$50',
      },
      {
        id: 9,
        doctor_name: 'Sofia Brient',
        speciality: 'Flow Chart',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        Earned: '3700.00',
        Education: 'Digital Marketer',
        Available: ' Available on Fri, 22 Mar ',
        Price: '$260',
        status: '1',
        profile: 'assets/img/user/user9.jpg',
        type: 'Male',
        location: 'Florida, USA',
        availableTime: '11 am',
        consulting_fees: '$600',
        booking_fees: '$500',
        video_call: '$50',
      },
    ];

    let mentees = [
      {
        id: '1',
        key: '16',
        name: 'Richard Wilson',
        age: '38',
        course: 'Integrated Sum',
        address: 'Alabama, USA',
        phone: '1 952 001 8563',
        email: 'richardwilson@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '100.00',
        earned: '3700.00',
        bloodgroup: 'AB+',
        type: 'Male',
        status: 'pending',
        img: 'assets/img/user/user.jpg',
      },
      {
        id: '2',
        key: '01',
        name: 'Charlene Reed',
        age: '29',
        course: 'Flow chart',
        address: 'North Carolina, USA',
        phone: '1 828 632 9170',
        email: 'Charlene@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '100.00',
        earned: '3400.00',
        bloodgroup: 'o+',
        type: 'Female',
        status: 'rejected',
        img: 'assets/img/user/user1.jpg',
      },
      {
        id: '3',
        key: '15',
        name: 'Travis Trimble',
        age: '23',
        course: 'Maths',
        address: 'Maine, USA',
        phone: '1 207 729 9974',
        email: 'travis@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '250.00',
        earned: '7000.00',
        bloodgroup: 'B+',
        type: 'Male',
        status: 'accepted',
        img: 'assets/img/user/user2.jpg',
      },
      {
        id: '4',
        key: '03',
        name: 'Carl Kelly',
        age: '29',
        course: 'Business Maths',
        address: 'Indiana, USA',
        phone: '1 260 724 7769',
        email: 'carlkelly@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '200.00',
        earned: '3000.00',
        bloodgroup: 'A+',
        type: 'Male',
        status: 'rejected',
        img: 'assets/img/user/user3.jpg',
      },
      {
        id: '5',
        key: '04',
        name: 'Michelle Fairfax',
        age: '25',
        course: 'Basic Calculation',
        address: 'Indiana, USA',
        phone: '1 504 368 6874',
        email: 'michelle@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '150.00',
        earned: '1000.00',
        bloodgroup: 'B+',
        type: 'Male',
        status: 'pending',
        img: 'assets/img/user/user4.jpg',
      },
      {
        id: '6',
        key: '05',
        name: 'Gina Moore',
        age: '23',
        course: 'Math Grade II',
        address: 'Florida, USA',
        phone: '9548207887',
        email: 'Elsie@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '350.00',
        earned: '3700.00',
        bloodgroup: 'o-',
        type: 'Male',
        status: 'accepted',
        img: 'assets/img/user/user5.jpg',
      },
      {
        id: '7',
        key: '06',
        name: 'Elsie Gilley',
        age: '16',
        course: 'Maths',
        address: 'Kentucky, USA',
        phone: '9548207887',
        email: 'Elsie@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '350.00',
        earned: '5000.00',
        bloodgroup: 'o-',
        type: 'Male',
        status: 'pending',
        img: 'assets/img/user/user6.jpg',
      },
      {
        id: '8',
        key: '07',
        name: 'Joan Gardner',
        age: '25',
        course: 'Flow chart',
        address: 'California, USA',
        phone: '9548207887',
        email: 'Elsie@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '350.00',
        earned: '3700.00',
        bloodgroup: 'o-',
        type: 'Male',
        status: 'accepted',
        img: 'assets/img/user/user7.jpg',
      },
      {
        id: '9',
        key: '08',
        name: 'Daniel Griffing',
        age: '21',
        course: 'Math Grade II',
        address: 'New Jersey, USA',
        phone: '9548207887',
        email: 'Elsie@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '350.00',
        earned: '2200.00',
        bloodgroup: 'o-',
        type: 'Male',
        status: 'accepted',
        img: 'assets/img/user/user8.jpg',
      },
      {
        id: '10',
        key: '09',
        name: 'Walter Roberson',
        age: '18',
        course: 'Algebra',
        address: 'Florida, USA',
        phone: '9548207887',
        email: 'Elsie@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '350.00',
        earned: '3700.00',
        bloodgroup: 'o-',
        type: 'Male',
        status: 'pending',
        img: 'assets/img/user/user9.jpg',
      },
      {
        id: '11',
        key: '16',
        name: 'Robert Rhodes',
        age: '19',
        course: 'Integrated Sum',
        address: 'California, USA',
        phone: '9548207887',
        email: 'Elsie@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '350.00',
        earned: '3700.00',
        bloodgroup: 'o-',
        type: 'Male',
        status: 'accepted',
        img: 'assets/img/user/user10.jpg',
      },
      {
        id: '13',
        key: '011',
        name: 'Harry Williams',
        age: '9',
        course: 'Algebra',
        address: 'Colorado, USA',
        phone: '1 303 607 7075',
        email: 'harrywilliams@example.com',
        since: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        lastvisit: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        paid: '350.00',
        earned: '3700.00',
        bloodgroup: 'A-',
        type: 'Male',
        status: 'accepted',
        img: 'assets/img/user/user11.jpg',
      },
    ];

    let reviews = [
      {
        id: 1,
        patient_name: 'Michelle Fairfax',
        doctor_name: 'Sofia Brient',
        patient_pic: 'assets/img/user/user4.jpg',
        doctor_pic: 'assets/img/user/user6.jpg',
        ratings: '5',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
      {
        id: 2,
        patient_name: 'Carl Kelly',
        doctor_name: 'Deborah Angel',
        patient_pic: 'assets/img/user/user5.jpg',
        doctor_pic: 'assets/img/user/user7.jpg',
        ratings: '4',
        description: '',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
      {
        id: 3,
        patient_name: 'Charlene Reed',
        doctor_name: 'Ruby Perrin',
        patient_pic: 'assets/img/user/useer6.jpg',
        doctor_pic: 'assets/img/user/user8.jpg',
        ratings: '4',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
      {
        id: 4,
        patient_name: 'Daniel Griffing',
        doctor_name: 'Paul Richard',
        patient_pic: 'assets/img/user/user7.jpg',
        doctor_pic: 'assets/img/user/user9.jpg',
        ratings: '4',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
      {
        id: 5,
        patient_name: 'Elsie Gilley',
        doctor_name: 'Katharine Berthold',
        patient_pic: 'assets/img/user/user10.jpg',
        doctor_pic: 'assets/img/user/user11.jpg',
        ratings: '3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
      {
        id: 6,
        patient_name: 'Elsie Gilley',
        doctor_name: 'Katharine Berthold',
        patient_pic: 'assets/img/user/user12.jpg',
        doctor_pic: 'assets/img/user/user13.jpg',
        ratings: '3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
      {
        id: 7,
        patient_name: 'Gina Moore',
        doctor_name: 'Marvin Campbell',
        patient_pic: 'assets/img/user/user14.jpg',
        doctor_pic: 'assets/img/user/user15.jpg',
        ratings: '3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
      {
        id: 8,
        patient_name: 'Harry Williams',
        doctor_name: 'Olga Barlow',
        patient_pic: 'assets/img/user/user.jpg',
        doctor_pic: 'assets/img/user/user1.jpg',
        ratings: '3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
      {
        id: 9,
        patient_name: 'Joan Gardner',
        doctor_name: 'Linda Tobin',
        patient_pic: 'assets/img/user/user2.jpg',
        doctor_pic: 'assets/img/user/user3.jpg',
        ratings: '3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
      {
        id: 10,
        patient_name: 'Travis Trimble',
        doctor_name: 'Darren Elder',
        patient_pic: 'assets/img/user/user4.jpg',
        doctor_pic: 'assets/img/user/user5.jpg',
        ratings: '3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        date: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
      },
    ];

    let comments = [
      {
        name: 'Michelle Fairfax',
        email: 'Fairfax@example.com',
        comment:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae, gravida pellentesque urna varius vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        name: 'Elsie Gilley',
        email: 'Fairfax@example.com',
        comment:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae, gravida pellentesque urna varius vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
    ];

    let blogs = [
      {
        id: 1,
        title: 'What is Lorem Ipsum? Lorem Ipsum is simply',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'Tyrone Roberts',
        createdAt: 'Wed Dec 3 2019 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'Java Script',
        status: 'active',
        img: 'assets/img/blog/blog-01.jpg',
        doctor_name: 'Tyrone Roberts',
        doctor_pic: 'assets/img/user/user6.jpg',
      },
      {
        id: 2,
        title: 'Contrary to popular belief, Lorem Ipsum is',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'Brittany Garcia',
        createdAt: 'Wed Dec 3 2019 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'HTML',
        status: 'active',
        img: 'assets/img/blog/blog-02.jpg',
        doctor_name: 'Brittany Garcia',
        doctor_pic: 'assets/img/user/user7.jpg',
      },
      {
        id: 3,
        title: 'The standard chunk of Lorem Ipsum used',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'Allen Davis',
        createdAt: 'Wed Dec 2 2019 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'C++',
        status: 'Inactive',
        img: 'assets/img/blog/blog-03.jpg',
        doctor_name: 'Allen Davis',
        doctor_pic: 'assets/img/user/user8.jpg',
      },
      {
        id: 4,
        title: 'The standard Lorem Ipsum passage, used',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'William Lawrence',
        createdAt: 'Wed Dec 1 2019 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'C',
        status: 'active',
        img: 'assets/img/blog/blog-04.jpg',
        doctor_name: 'William Lawrence',
        doctor_pic: 'assets/img/user/user9.jpg',
      },
      {
        id: 5,
        title: 'Abacus Study for beginner - Part II',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'Marvin Campbell',
        createdAt: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'CSS',
        status: 'Inactive',
        img: 'assets/img/blog/blog-05.jpg',
        doctor_name: 'Marvin Campbell',
        doctor_pic: 'assets/img/user/user10.jpg',
      },
      {
        id: 6,
        title: 'Abacus Study for beginner - Part III',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'Sofia Brient',
        createdAt: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'ASP .Net',
        status: 'active',
        img: 'assets/img/blog/blog-06.jpg',
        doctor_name: 'Katharine Berthold',
        doctor_pic: 'assets/img/user/user11.jpg',
      },
      {
        id: 7,
        title: 'Choose your own Online Doctor Appointment',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'Sofia Brient',
        createdAt: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'Angular',
        status: 'active',
        img: 'assets/img/blog/blog-07.jpg',
        doctor_name: 'Linda Tobin',
        doctor_pic: 'assets/img/user/user12.jpg',
      },
      {
        id: 8,
        title: 'Simple steps to visit your mentor today',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'Sofia Brient',
        createdAt: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'VB .Net',
        status: 'active',
        img: 'assets/img/blog/blog-08.jpg',
        doctor_name: 'Paul Richard ',
        doctor_pic: 'assets/img/user/user13.jpg',
      },
      {
        id: 9,
        title: '5 Great reasons to use an Online Doctor',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'Sofia Brient',
        createdAt: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'jQuery',
        status: 'active',
        img: 'assets/img/blog/blog-09.jpg',
        doctor_name: 'John Gibbs ',
        doctor_pic: 'assets/img/user/user14.jpg',
      },
      {
        id: 10,
        title: 'Online Doctoral Programs',
        short_desc:
          'Lorem ipsum dolor sit amet, consectetur em adipiscing elit, sed do eiusmod tempor.',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco sit laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        createdBy: 'Sofia Brient',
        createdAt: 'Wed May 27 2020 09:41:48 GMT+0530 (India Standard Time)',
        comments: 12,
        type: 'MySQL',
        status: 'active',
        img: 'assets/img/blog/blog-10.jpg',
        doctor_name: 'Olga Barlow',
        doctor_pic: 'assets/img/user/user15.jpg',
      },
    ];

    let tags = [
      {
        id: 1,
        name: 'HTML',
        ratings: 27,
      },
      {
        id: 2,
        name: 'CSS',
        ratings: 21,
      },
      {
        id: 3,
        name: 'Java Script',
        ratings: 20,
      },
      {
        id: 4,
        name: 'jQuery',
        ratings: 30,
      },
      {
        id: 5,
        name: 'Wordpress',
        ratings: 12,
      },
      {
        id: 6,
        name: 'PHP',
        ratings: 45,
      },
      {
        id: 7,
        name: 'Angular js',
        ratings: 56,
      },
      {
        id: 8,
        name: 'React js',
        ratings: 43,
      },
      {
        id: 9,
        name: 'Vue js',
        ratings: 76,
      },
      {
        id: 10,
        name: 'JSON',
        ratings: 31,
      },
      {
        id: 11,
        name: 'Vb',
        ratings: 30,
      },
      {
        id: 12,
        name: 'C++',
        ratings: 50,
      },
      {
        id: 13,
        name: 'Asp.net',
        ratings: 34,
      },
      {
        id: 14,
        name: 'C',
        ratings: 45,
      },
    ];

    let transactions = [
      {
        id: 1,
        invoiceNumber: '#INV-0001',
        patient_id: '01',
        patient_name: 'Daniel Griffing',
        profile: 'assets/img/user/user.jpg',
        total_amount: '$150.00',
        status: 'paid',
      },
      {
        id: 2,
        invoiceNumber: '#INV-0002',
        patient_id: '07',
        patient_name: 'Joan Gardner',
        profile: 'assets/img/user/user1.jpg',
        total_amount: '$250.00',
        status: 'paid',
      },
      {
        id: 3,
        invoiceNumber: '#INV-0003',
        patient_id: '04',
        patient_name: 'Michelle Fairfax',
        profile: 'assets/img/user/user2.jpg',
        total_amount: '$150.00',
        status: 'paid',
      },
      {
        id: 4,
        invoiceNumber: '#INV-0004',
        patient_id: '03',
        patient_name: 'Carl Kelly',
        profile: 'assets/img/user/user3.jpg',
        total_amount: '$150.00',
        status: 'paid',
      },
      {
        id: 5,
        invoiceNumber: '#INV-0005',
        patient_id: '01',
        patient_name: 'Elsie Gilley',
        profile: 'assets/img/user/user4.jpg',
        total_amount: '$300.00',
        status: 'paid',
      },
      {
        id: 6,
        invoiceNumber: '#INV-0006',
        patient_id: '05',
        patient_name: 'Gina Moore',
        profile: 'assets/img/user/user5.jpg',
        total_amount: '$350.00',
        status: 'paid',
      },
      {
        id: 7,
        invoiceNumber: '#INV-0007',
        patient_id: '16',
        patient_name: 'Robert Rhodes',
        profile: 'assets/img/user/user6.jpg',
        total_amount: '$120.00',
        status: 'paid',
      },
      {
        id: 8,
        invoiceNumber: '#INV-0008',
        patient_id: '15',
        patient_name: 'Travis Trimble',
        profile: 'assets/img/user/user7.jpg',
        total_amount: '$200.00',
        status: 'paid',
      },
      {
        id: 9,
        invoiceNumber: '#INV-0009',
        patient_id: '09',
        patient_name: 'Walter Roberson',
        profile: 'assets/img/user/user8.jpg',
        total_amount: '$100.00',
        status: 'paid',
      },
    ];
    let positions = [
      {
        id: 1,
        name: 'Digital Marketer',
        img: 'assets/img/path-img1.jpg',
      },
      {
        id: 2,
        name: 'UI designer',
        img: 'assets/img/path-img2.jpg',
      },
      {
        id: 3,
        name: 'IT Security',
        img: 'assets/img/path-img3.jpg',
      },
      {
        id: 4,
        name: 'Front-End Developer',
        img: 'assets/img/path-img4.jpg',
      },
      {
        id: 5,
        name: 'Web Developer',
        img: 'assets/img/path-img5.jpg',
      },
      {
        id: 6,
        name: 'Administrator',
        img: 'assets/img/path-img6.jpg',
      },
      {
        id: 7,
        name: 'Project Manager',
        img: 'assets/img/path-img7.jpg',
      },
      {
        id: 8,
        name: 'PHP Developer',
        img: 'assets/img/path-img8.jpg',
      },
    ];
    return {
      transactions: transactions,
      comments: comments,
      favourites: favourites,
      blogs: blogs,
      specialityList: specialityList,
      appointments: appointments,
      mentors: mentors,
      mentees: mentees,
      reviews: reviews,
      positions: positions,
      tags: tags,
    };
  }
}
